### ISSUE TITLE
运行不了的

### ISSUE THREAD

**Issue by DavidMGT** [javico2609/flutter-challenges#2]
Configuring the default Firebase app...
6.0.0 - [Firebase/Core][I-COR000004] App with name __FIRAPP_DEFAULT does not exist.
6.0.0 - [Firebase/Core][I-COR000012] Could not locate configuration file: 'GoogleService-Info.plist'.
6.0.0 - [Firebase/Core][I-COR000005] No app has been configured yet.
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000113a7c1bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x0000000112ba6735 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000113a7c015 +[NSException raise:format:] + 197
	3   Runner                              0x000000010f02c260 +[FIRApp configure] + 576
	4   Runner                              0x000000010f0c0ad9 -[FLTFirebaseAuthPlugin init] + 217
	5   Runner                              0x000000010f0c092d +[FLTFirebaseAuthPlugin registerWithRegistrar:] + 173
	6   Runner                              0x000000010efcf1af +[GeneratedPluginRegistrant registerWithRegistry:] + 223
	7   Runner                            <…>

**Comment by DavidMGT** [comment]
![1](https://user-images.githubusercontent.com/12042191/58007098-1994e580-7b1c-11e9-887d-354dc46d874f.png)

**Comment by javico2609** [comment]
Hi, this project have only Android firebase config, you need config your own firebase for iOS or disable that feature
