### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by AkoWu101** [javico2609/flutter-challenges#5]
Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    <unknown>:0: error: module map file '/Users/kingwu/Downloads/flutter-challenges-master/build/ios/Debug-iphonesimulator/mapbox_gl/mapbox_gl.modulemap' not found
    <unknown>:0: error: module map file '/Users/kingwu/Downloads/flutter-challenges-master/build/ios/Debug-iphonesimulator/mapbox_gl/mapbox_gl.modulemap' not found
    2 errors generated.
    <unknown>:0: error: failed to emit precompiled header '/Users/kingwu/Library/Developer/Xcode/DerivedData/Runner-cjocfzzikqtrjpbujtqizppxzpiz/Build/Intermediates.noindex/PrecompiledHeaders/Runner-Bridging-Header-swift_921O44N4TOMW-clang_1DSMN03GK5GSR.pch' for bridging header '/Users/kingwu/Downloads/flutter-challenges-master/ios/Runner/Runner-Bridging-Header.h'
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    <unknown>:0: error: generate-pch command failed with exit code 1 (use -v to see invocation)

Could not build the application for the simulator.
Error launching application on iPhone Xʀ.

**Comment by javico2609** [comment]
Hi @KingWu . thx for using this repo, 
It only support Android for now, you need add extra config for ios compile.
try this repo on android emulator.
