### ISSUE TITLE
Class GetIt doesn't have a default constructor

### ISSUE THREAD

**Issue by jpollone** [javico2609/flutter-challenges#7]
Hi, I just wanted to play around, but I show an error that says GetIt doesn't have a constructor. Do you have any tips on how to solve this? 

<img width="1973" alt="getit-constructor" src="https://user-images.githubusercontent.com/957276/64489226-9c9e9080-d21e-11e9-84c7-f6f3cbc756eb.png">

**Comment by javico2609** [comment]
Hi, thx for using flutter_challenges repo, can you update your code base on this repo ? i fixed this issue

**Comment by jpollone** [comment]
Thank you, Javier. I pulled and cleaned, but also had to restart Studio for some reason. In any case, thank you for fixing and I am now able to compile view in the simulator. I appreciate you sharing your knowledge for beginners like myself.
